const MINIMUM_WINDOW_SHORT_EDGE = 700;
const MINIMUM_WINDOW_LONG_EDGE = 1000;
const FILE_ID_FOR_SOUND_AND_MUSIC_VOLUME = 1;
const FILE_ID_FOR_SESSION_STATE = 2;
const STANDARD_BACKGROUND_COLOR = { r: 225, g: 225, b: 225, alpha: 255 };
export { MINIMUM_WINDOW_SHORT_EDGE, MINIMUM_WINDOW_LONG_EDGE, FILE_ID_FOR_SOUND_AND_MUSIC_VOLUME, FILE_ID_FOR_SESSION_STATE, STANDARD_BACKGROUND_COLOR };
